language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - "export MONGOHQ_URL='mongodb://localhost:6379/test'"
  - "export ROOT_URL='http://localhost:5000/'"
  - "node server.js > server_log &"
  - "sleep 3"
after_script:
  - "echo 'Server Log:'"
  - "cat server_log"
